// ─── SkyBooker Design Tokens ──────────────────────────────────────────────────
export const colors = {
  primary:    '#e63946',
  primaryDark:'#c1121f',
  primaryDeep:'#780000',
  accent:     '#ffd60a',
  white:      '#ffffff',
  bg:         '#f5f5f5',
  card:       '#ffffff',
  border:     '#f0f0f0',
  text:       '#222222',
  textMuted:  '#999999',
  textLight:  '#bbbbbb',
  success:    '#2e7d32',
  successBg:  '#e8f5e9',
  error:      '#c62828',
  errorBg:    '#fce4ec',
  warning:    '#e65100',
  warningBg:  '#fff3e0',
};

export const s = {
  // Layout
  app: {
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    minHeight: '100vh',
    background: colors.bg,
    color: colors.text,
  },
  main: { maxWidth: 1100, margin: '0 auto', padding: '32px 24px' },

  // Navbar
  nav: {
    background: `linear-gradient(135deg, ${colors.primary} 0%, ${colors.primaryDark} 100%)`,
    padding: '0 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 60,
    boxShadow: '0 2px 12px rgba(230,57,70,0.3)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  logo: { color: colors.white, fontWeight: 800, fontSize: 22, letterSpacing: '-0.5px', cursor: 'pointer' },
  logoAccent: { color: colors.accent },
  navLinks: { display: 'flex', gap: 8, alignItems: 'center' },
  navBtn: (active) => ({
    background: active ? 'rgba(255,255,255,0.25)' : 'transparent',
    border: active ? '1px solid rgba(255,255,255,0.5)' : '1px solid transparent',
    color: colors.white,
    padding: '6px 14px',
    borderRadius: 20,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    transition: 'all 0.2s',
  }),

  // Hero
  hero: {
    background: `linear-gradient(160deg, ${colors.primary} 0%, ${colors.primaryDark} 60%, ${colors.primaryDeep} 100%)`,
    padding: '48px 24px 80px',
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  heroTitle: { color: colors.white, fontSize: 36, fontWeight: 800, margin: '0 0 8px', textShadow: '0 2px 8px rgba(0,0,0,0.2)' },
  heroSub: { color: 'rgba(255,255,255,0.85)', fontSize: 16, margin: '0 0 32px' },

  // Search Card
  searchCard: {
    background: colors.white,
    borderRadius: 16,
    padding: 24,
    maxWidth: 900,
    margin: '0 auto',
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
    position: 'relative',
    zIndex: 2,
  },
  tabs: { display: 'flex', gap: 4, marginBottom: 20 },
  tab: (active) => ({
    background: active ? colors.primary : '#f0f0f0',
    color: active ? colors.white : '#666',
    border: 'none',
    padding: '8px 20px',
    borderRadius: 20,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    transition: 'all 0.2s',
  }),
  searchGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr auto auto',
    gap: 12,
    alignItems: 'end',
  },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 11, fontWeight: 700, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  input: {
    border: '2px solid #e8e8e8',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 15,
    fontWeight: 600,
    outline: 'none',
    transition: 'border-color 0.2s',
    width: '100%',
    boxSizing: 'border-box',
    background: '#fafafa',
  },
  swapBtn: {
    background: colors.white,
    border: `2px solid ${colors.primary}`,
    borderRadius: '50%',
    width: 36,
    height: 36,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: colors.primary,
    fontSize: 18,
    fontWeight: 700,
    flexShrink: 0,
    alignSelf: 'center',
    marginTop: 16,
  },
  searchBtn: {
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: colors.white,
    border: 'none',
    borderRadius: 8,
    padding: '12px 28px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 4px 15px rgba(230,57,70,0.4)',
    transition: 'transform 0.1s',
    whiteSpace: 'nowrap',
    alignSelf: 'flex-end',
  },

  // Cards
  card: {
    background: colors.white,
    borderRadius: 12,
    padding: '20px 24px',
    marginBottom: 12,
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    border: `1px solid ${colors.border}`,
    transition: 'box-shadow 0.2s, transform 0.2s',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: colors.text,
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },

  // Buttons
  btn: {
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: colors.white,
    border: 'none',
    borderRadius: 8,
    padding: '10px 20px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 3px 10px rgba(230,57,70,0.3)',
  },
  btnOutline: {
    background: '#f5f5f5',
    color: '#666',
    border: '1px solid #ddd',
    borderRadius: 8,
    padding: '10px 20px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnDanger: {
    background: '#f5f5f5',
    color: colors.primary,
    border: `2px solid ${colors.primary}`,
    borderRadius: 8,
    padding: '12px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    width: '100%',
  },
  submitBtn: {
    width: '100%',
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: colors.white,
    border: 'none',
    borderRadius: 8,
    padding: '12px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    marginTop: 8,
    boxShadow: '0 4px 15px rgba(230,57,70,0.35)',
  },

  // Badges
  badge: (type) => ({
    background: type === 'success' ? colors.successBg : type === 'error' ? colors.errorBg : colors.warningBg,
    color: type === 'success' ? colors.success : type === 'error' ? colors.error : colors.warning,
    fontSize: 11,
    fontWeight: 700,
    padding: '3px 8px',
    borderRadius: 4,
    display: 'inline-block',
  }),

  // Alerts
  alert: (type) => ({
    background: type === 'error' ? colors.errorBg : colors.successBg,
    color: type === 'error' ? colors.error : colors.success,
    border: `1px solid ${type === 'error' ? '#ef9a9a' : '#a5d6a7'}`,
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    marginBottom: 16,
    fontWeight: 500,
  }),

  // Modal
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modal: {
    background: colors.white,
    borderRadius: 16,
    padding: 32,
    width: '100%',
    maxWidth: 480,
    maxHeight: '90vh',
    overflowY: 'auto',
    position: 'relative',
  },
  modalTitle: { fontSize: 22, fontWeight: 800, margin: '0 0 24px', color: colors.text },
  closeBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    background: '#f5f5f5',
    border: 'none',
    borderRadius: '50%',
    width: 32,
    height: 32,
    cursor: 'pointer',
    fontSize: 18,
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Form
  formGroup: { marginBottom: 16 },
  formLabel: { display: 'block', fontSize: 12, fontWeight: 700, color: '#666', marginBottom: 6, textTransform: 'uppercase' },
  formInput: {
    width: '100%',
    border: '2px solid #e8e8e8',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },

  // Misc
  spinner: {
    width: 36,
    height: 36,
    border: '4px solid #f0f0f0',
    borderTop: `4px solid ${colors.primary}`,
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    margin: '40px auto',
  },
  emptyState: { textAlign: 'center', padding: '60px 20px', color: colors.textMuted },
  avatar: {
    width: 80,
    height: 80,
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.white,
    fontSize: 32,
    fontWeight: 800,
    margin: '0 auto 20px',
  },
};
